version: "3"

services:
  prometheus:
    image: prom/prometheus
    user: root
    restart: always
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "9090:9090"
    container_name: prometheus
    networks:
      - "app-net"
    
  flask:
    build:
      context: ./apps/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./apps:/app"
    ports:
      - "5001:5001"
    container_name: flask
    networks:
      - "app-net"
  
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - "grafana-data:/var/lib/grafana"
    ports:
      - "3000:3000"
    user: root
    container_name: grafana
    networks:
      - "app-net"

volumes:
  grafana-data: {}

networks:
  app-net: {}
